export const restaurant=[
  {
    "restaurant_id": 6317637,
    "restaurant_name": "Le Petit Souffle",
    "cuisines": "French, Japanese, Desserts",
    "average_costfortwo": 1100,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4.8,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 314
  },
  {
    "restaurant_id": 6304287,
    "restaurant_name": "Izakaya Kikufuji",
    "cuisines": "Japanese",
    "average_costfortwo": 1200,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4.5,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 591
  },
  {
    "restaurant_id": 6300002,
    "restaurant_name": "Heat - Edsa Shangri-La",
    "cuisines": "Seafood, Asian, Filipino, Indian",
    "average_costfortwo": 4000,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4.4,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 270
  },
  {
    "restaurant_id": 6318506,
    "restaurant_name": "Ooma",
    "cuisines": "Japanese, Sushi",
    "average_costfortwo": 1500,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.9,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 365
  },
  {
    "restaurant_id": 6314302,
    "restaurant_name": "Sambo Kojin",
    "cuisines": "Japanese, Korean",
    "average_costfortwo": 1500,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4.8,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 229
  },
  {
    "restaurant_id": 18189371,
    "restaurant_name": "Din Tai Fung",
    "cuisines": "Chinese",
    "average_costfortwo": 1000,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.4,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 336
  },
  {
    "restaurant_id": 6300781,
    "restaurant_name": "Buffet 101",
    "cuisines": "Asian, European",
    "average_costfortwo": 2000,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 520
  },
  {
    "restaurant_id": 6301290,
    "restaurant_name": "Vikings",
    "cuisines": "Seafood, Filipino, Asian, European",
    "average_costfortwo": 2000,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4.2,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 677
  },
  {
    "restaurant_id": 6300010,
    "restaurant_name": "Spiral - Sofitel Philippine Plaza Manila",
    "cuisines": "European, Asian, Indian",
    "average_costfortwo": 6000,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4.9,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 621
  },
  {
    "restaurant_id": 6314987,
    "restaurant_name": "Locavore",
    "cuisines": "Filipino",
    "average_costfortwo": 1100,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4.8,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 532
  },
  {
    "restaurant_id": 6309903,
    "restaurant_name": "Silantro Fil-Mex",
    "cuisines": "Filipino, Mexican",
    "average_costfortwo": 800,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.9,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 1070
  },
  {
    "restaurant_id": 6309455,
    "restaurant_name": "Mad Mark's Creamery & Good Eats",
    "cuisines": "American, Ice Cream, Desserts",
    "average_costfortwo": 900,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4.2,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 488
  },
  {
    "restaurant_id": 6318433,
    "restaurant_name": "Silantro Fil-Mex",
    "cuisines": "Filipino, Mexican",
    "average_costfortwo": 800,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.8,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 294
  },
  {
    "restaurant_id": 6310470,
    "restaurant_name": "Guevarra's",
    "cuisines": "Filipino",
    "average_costfortwo": 1000,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4.2,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 458
  },
  {
    "restaurant_id": 6314605,
    "restaurant_name": "Sodam Korean Restaurant",
    "cuisines": "Korean",
    "average_costfortwo": 700,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.3,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 223
  },
  {
    "restaurant_id": 18185059,
    "restaurant_name": "Cafe Arabelle",
    "cuisines": "Cafe, American, Italian, Filipino",
    "average_costfortwo": 800,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.6,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 29
  },
  {
    "restaurant_id": 18182702,
    "restaurant_name": "Nonna's Pasta & Pizzeria",
    "cuisines": "Italian, Pizza",
    "average_costfortwo": 850,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 72
  },
  {
    "restaurant_id": 6318213,
    "restaurant_name": "Balay Dako",
    "cuisines": "Filipino",
    "average_costfortwo": 1200,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4.5,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 211
  },
  {
    "restaurant_id": 18255654,
    "restaurant_name": "Hobing Korean Dessert Cafe",
    "cuisines": "Cafe, Korean, Desserts",
    "average_costfortwo": 600,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.5,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 118
  },
  {
    "restaurant_id": 6308205,
    "restaurant_name": "Wildflour Cafe + Bakery",
    "cuisines": "Cafe, Bakery, American, Italian",
    "average_costfortwo": 1500,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4.4,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 392
  },
  {
    "restaurant_id": 6315438,
    "restaurant_name": "NIU by Vikings",
    "cuisines": "Seafood, American, Mediterranean, Japanese",
    "average_costfortwo": 3000,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4.7,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 535
  },
  {
    "restaurant_id": 6310406,
    "restaurant_name": "The Food Hall by Todd English",
    "cuisines": "American, Asian, Italian, Seafood",
    "average_costfortwo": 1800,
    "currency": "Botswana Pula(P)",
    "has_tablebooking": "Yes",
    "has_online_delivery": "No",
    "aggregate_rating": 4.5,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 618
  },
  {
    "restaurant_id": 6600681,
    "restaurant_name": "Chez Michou",
    "cuisines": "Fast Food, French",
    "average_costfortwo": 55,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 6
  },
  {
    "restaurant_id": 6601005,
    "restaurant_name": "Caf� Daniel Briand",
    "cuisines": "Cafe",
    "average_costfortwo": 30,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.8,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 9
  },
  {
    "restaurant_id": 6600292,
    "restaurant_name": "Casa do Biscoito Mineiro",
    "cuisines": "Bakery",
    "average_costfortwo": 45,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.7,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 11
  },
  {
    "restaurant_id": 6600441,
    "restaurant_name": "Maori",
    "cuisines": "Brazilian",
    "average_costfortwo": 60,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.8,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 11
  },
  {
    "restaurant_id": 6600970,
    "restaurant_name": "Pizza �� Bessa",
    "cuisines": "Pizza",
    "average_costfortwo": 50,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.2,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 11
  },
  {
    "restaurant_id": 6600379,
    "restaurant_name": "Sushi Loko",
    "cuisines": "Japanese",
    "average_costfortwo": 80,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.1,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 10
  },
  {
    "restaurant_id": 6600214,
    "restaurant_name": "Beirute",
    "cuisines": "Arabian",
    "average_costfortwo": 90,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.7,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 8
  },
  {
    "restaurant_id": 6601218,
    "restaurant_name": "New Koto",
    "cuisines": "Japanese",
    "average_costfortwo": 200,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.7,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 5
  },
  {
    "restaurant_id": 6600060,
    "restaurant_name": "Sandubas Caf�",
    "cuisines": "Brazilian, Cafe",
    "average_costfortwo": 30,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 0,
    "rating_color": "White",
    "rating_text": "Not rated",
    "votes": 2
  },
  {
    "restaurant_id": 6600083,
    "restaurant_name": "Villa Tevere",
    "cuisines": "Italian",
    "average_costfortwo": 150,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.1,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 12
  },
  {
    "restaurant_id": 6601515,
    "restaurant_name": "Rovereto",
    "cuisines": "Pizza",
    "average_costfortwo": 100,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.1,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 9
  },
  {
    "restaurant_id": 6601361,
    "restaurant_name": "Buena Carne",
    "cuisines": "Bar Food, Brazilian",
    "average_costfortwo": 60,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.6,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 9
  },
  {
    "restaurant_id": 6601602,
    "restaurant_name": "Taco Pep",
    "cuisines": "Mexican, Grill",
    "average_costfortwo": 100,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.3,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 29
  },
  {
    "restaurant_id": 6601589,
    "restaurant_name": "Coco Bambu",
    "cuisines": "International",
    "average_costfortwo": 230,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.2,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 17
  },
  {
    "restaurant_id": 6601862,
    "restaurant_name": "Tayp��",
    "cuisines": "Peruvian, Latin American",
    "average_costfortwo": 100,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.6,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 5
  },
  {
    "restaurant_id": 6601595,
    "restaurant_name": "Outback Steakhouse",
    "cuisines": "American, Grill",
    "average_costfortwo": 150,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 10
  },
  {
    "restaurant_id": 6601158,
    "restaurant_name": "Manzu��",
    "cuisines": "Seafood",
    "average_costfortwo": 240,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.2,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 6
  },
  {
    "restaurant_id": 6600427,
    "restaurant_name": "Coco Bambu",
    "cuisines": "International",
    "average_costfortwo": 230,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.9,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 30
  },
  {
    "restaurant_id": 6600116,
    "restaurant_name": "Gero",
    "cuisines": "Italian",
    "average_costfortwo": 350,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.3,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 8
  },
  {
    "restaurant_id": 6601457,
    "restaurant_name": "Brazilian American Burgers",
    "cuisines": "American, Burger",
    "average_costfortwo": 50,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.6,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 9
  },
  {
    "restaurant_id": 7303219,
    "restaurant_name": "Pesqueiro Eco Gourmet",
    "cuisines": "Seafood, Bar Food, Brazilian",
    "average_costfortwo": 140,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 7
  },
  {
    "restaurant_id": 7304307,
    "restaurant_name": "Confeitaria Colombo",
    "cuisines": "Desserts, Cafe",
    "average_costfortwo": 100,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.8,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 29
  },
  {
    "restaurant_id": 7301215,
    "restaurant_name": "Bibi",
    "cuisines": "Juices, Healthy Food",
    "average_costfortwo": 60,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.7,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 24
  },
  {
    "restaurant_id": 7300596,
    "restaurant_name": "Cervantes",
    "cuisines": "Beverages, Bar Food, Fast Food",
    "average_costfortwo": 90,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.5,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 29
  },
  {
    "restaurant_id": 7300612,
    "restaurant_name": "Amir",
    "cuisines": "Lebanese",
    "average_costfortwo": 170,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.2,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 11
  },
  {
    "restaurant_id": 7300704,
    "restaurant_name": "TT Burger",
    "cuisines": "Burger",
    "average_costfortwo": 60,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.8,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 19
  },
  {
    "restaurant_id": 7300955,
    "restaurant_name": "Braseiro da G��vea",
    "cuisines": "Brazilian, Bar Food",
    "average_costfortwo": 100,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.9,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 40
  },
  {
    "restaurant_id": 7300521,
    "restaurant_name": "Balada Mix",
    "cuisines": "Brazilian, Healthy Food, Juices, Pizza",
    "average_costfortwo": 90,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.6,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 21
  },
  {
    "restaurant_id": 7300515,
    "restaurant_name": "Garota de Ipanema",
    "cuisines": "Brazilian, Bar Food",
    "average_costfortwo": 120,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.9,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 49
  },
  {
    "restaurant_id": 7300483,
    "restaurant_name": "Zaz�� Bistr�� Tropical",
    "cuisines": "Brazilian",
    "average_costfortwo": 170,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.6,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 21
  },
  {
    "restaurant_id": 7301064,
    "restaurant_name": "Fil� de Ouro",
    "cuisines": "Brazilian",
    "average_costfortwo": 90,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.3,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 14
  },
  {
    "restaurant_id": 7304312,
    "restaurant_name": "D.O.C Ristorante",
    "cuisines": "Italian",
    "average_costfortwo": 150,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 5
  },
  {
    "restaurant_id": 7300004,
    "restaurant_name": "Sushi Leblon",
    "cuisines": "Japanese",
    "average_costfortwo": 250,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.6,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 25
  },
  {
    "restaurant_id": 7300868,
    "restaurant_name": "Talho Capixaba",
    "cuisines": "Bakery, Sandwich, Brazilian",
    "average_costfortwo": 120,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.4,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 13
  },
  {
    "restaurant_id": 7302637,
    "restaurant_name": "Leme Light",
    "cuisines": "Brazilian",
    "average_costfortwo": 40,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.2,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 7
  },
  {
    "restaurant_id": 7302140,
    "restaurant_name": "Shirley",
    "cuisines": "Brazilian, Seafood",
    "average_costfortwo": 250,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.2,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 8
  },
  {
    "restaurant_id": 7305048,
    "restaurant_name": "Quiosque Chopp Brahma",
    "cuisines": "Bar Food, Brazilian",
    "average_costfortwo": 70,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 0,
    "rating_color": "White",
    "rating_text": "Not rated",
    "votes": 1
  },
  {
    "restaurant_id": 7302898,
    "restaurant_name": "Apraz�_vel",
    "cuisines": "Brazilian",
    "average_costfortwo": 300,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.7,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 44
  },
  {
    "restaurant_id": 7302859,
    "restaurant_name": "Aconchego Carioca",
    "cuisines": "Brazilian, Bar Food",
    "average_costfortwo": 85,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.6,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 24
  },
  {
    "restaurant_id": 7301700,
    "restaurant_name": "Garota de Ipanema",
    "cuisines": "Brazilian, Bar Food",
    "average_costfortwo": 80,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.3,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 10
  },
  {
    "restaurant_id": 6706313,
    "restaurant_name": "Cantina Famiglia Mancini",
    "cuisines": "Italian, Pizza",
    "average_costfortwo": 250,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.5,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 49
  },
  {
    "restaurant_id": 6704326,
    "restaurant_name": "Templo da Carne - Marcos Bassi",
    "cuisines": "Steak, BBQ",
    "average_costfortwo": 250,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.4,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 17
  },
  {
    "restaurant_id": 6711179,
    "restaurant_name": "Gopala Hari",
    "cuisines": "Indian",
    "average_costfortwo": 70,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.1,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 5
  },
  {
    "restaurant_id": 6702797,
    "restaurant_name": "Jiquitaia",
    "cuisines": "Brazilian",
    "average_costfortwo": 100,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.1,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 15
  },
  {
    "restaurant_id": 6700475,
    "restaurant_name": "Skye - Hotel Unique",
    "cuisines": "Beverages, International",
    "average_costfortwo": 300,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.8,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 59
  },
  {
    "restaurant_id": 6713413,
    "restaurant_name": "Les 3 Brasseurs",
    "cuisines": "French, Brazilian, Beverages",
    "average_costfortwo": 120,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.6,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 30
  },
  {
    "restaurant_id": 6714340,
    "restaurant_name": "Red Steak & Burger",
    "cuisines": "Brazilian, Grill",
    "average_costfortwo": 75,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.9,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 5
  },
  {
    "restaurant_id": 6710645,
    "restaurant_name": "Cantinho da Gula",
    "cuisines": "Brazilian",
    "average_costfortwo": 55,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 0,
    "rating_color": "White",
    "rating_text": "Not rated",
    "votes": 0
  },
  {
    "restaurant_id": 6700402,
    "restaurant_name": "Paris 6 Classique",
    "cuisines": "French",
    "average_costfortwo": 200,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.4,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 73
  },
  {
    "restaurant_id": 6700846,
    "restaurant_name": "Kawa Sushi",
    "cuisines": "Sushi, Japanese",
    "average_costfortwo": 120,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.5,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 9
  },
  {
    "restaurant_id": 6702159,
    "restaurant_name": "A Figueira Rubaiyat",
    "cuisines": "BBQ, Grill, Brazilian",
    "average_costfortwo": 300,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.3,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 39
  },
  {
    "restaurant_id": 6711666,
    "restaurant_name": "Kinoshita",
    "cuisines": "Sushi",
    "average_costfortwo": 230,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.9,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 12
  },
  {
    "restaurant_id": 6701257,
    "restaurant_name": "Meats",
    "cuisines": "Gourmet Fast Food, Burger",
    "average_costfortwo": 120,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.3,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 68
  },
  {
    "restaurant_id": 6706211,
    "restaurant_name": "Paribar",
    "cuisines": "Brazilian, Italian",
    "average_costfortwo": 150,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.3,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 46
  },
  {
    "restaurant_id": 6705858,
    "restaurant_name": "Terra�_o It��lia",
    "cuisines": "Italian",
    "average_costfortwo": 400,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.4,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 37
  },
  {
    "restaurant_id": 6701419,
    "restaurant_name": "Divino Fog�o",
    "cuisines": "Brazilian, Mineira",
    "average_costfortwo": 65,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 0,
    "rating_color": "White",
    "rating_text": "Not rated",
    "votes": 2
  },
  {
    "restaurant_id": 6703956,
    "restaurant_name": "Super Grill",
    "cuisines": "Brazilian",
    "average_costfortwo": 50,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 0,
    "rating_color": "White",
    "rating_text": "Not rated",
    "votes": 2
  },
  {
    "restaurant_id": 6709580,
    "restaurant_name": "Esquina Mocot�_",
    "cuisines": "Brazilian, North Eastern",
    "average_costfortwo": 100,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.4,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 22
  },
  {
    "restaurant_id": 6703176,
    "restaurant_name": "Veloso",
    "cuisines": "Brazilian, Bar Food, Beverages",
    "average_costfortwo": 70,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.6,
    "rating_color": "Dark Green",
    "rating_text": "Excellent",
    "votes": 58
  },
  {
    "restaurant_id": 6713772,
    "restaurant_name": "Sainte Marie Gastronomia",
    "cuisines": "Lebanese, Arabian",
    "average_costfortwo": 120,
    "currency": "Brazilian Real(R$)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 4.1,
    "rating_color": "Green",
    "rating_text": "Very Good",
    "votes": 11
  },
  {
    "restaurant_id": 17284404,
    "restaurant_name": "Austin's BBQ and Oyster Bar",
    "cuisines": "BBQ, Burger, Seafood",
    "average_costfortwo": 25,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.3,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 35
  },
  {
    "restaurant_id": 17284203,
    "restaurant_name": "BJ's Country Buffet",
    "cuisines": "American, BBQ",
    "average_costfortwo": 10,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.3,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 25
  },
  {
    "restaurant_id": 17284105,
    "restaurant_name": "Cookie Shoppe",
    "cuisines": "",
    "average_costfortwo": 0,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.4,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 34
  },
  {
    "restaurant_id": 17284302,
    "restaurant_name": "El Vaquero Mexican Restaurant",
    "cuisines": "Mexican",
    "average_costfortwo": 0,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.4,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 45
  },
  {
    "restaurant_id": 17284397,
    "restaurant_name": "Elements Coffee Co - Northwest",
    "cuisines": "Coffee and Tea, Sandwich",
    "average_costfortwo": 10,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.4,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 26
  },
  {
    "restaurant_id": 17284211,
    "restaurant_name": "Pearly's Famous Country Cookng",
    "cuisines": "",
    "average_costfortwo": 0,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.4,
    "rating_color": "Orange",
    "rating_text": "Average",
    "votes": 36
  },
  {
    "restaurant_id": 17284094,
    "restaurant_name": "Chick-fil-A",
    "cuisines": "Fast Food",
    "average_costfortwo": 10,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.5,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 67
  },
  {
    "restaurant_id": 17284409,
    "restaurant_name": "Guang Zhou Chinese Restaurant",
    "cuisines": "Asian, Chinese, Vegetarian",
    "average_costfortwo": 10,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.9,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 141
  },
  {
    "restaurant_id": 17284139,
    "restaurant_name": "Harvest Moon",
    "cuisines": "Pizza, Bar Food, Sandwich",
    "average_costfortwo": 25,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.7,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 147
  },
  {
    "restaurant_id": 17284403,
    "restaurant_name": "Henry Campbell's Steakhouse",
    "cuisines": "Steak, Tapas, Bar Food",
    "average_costfortwo": 70,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.5,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 51
  },
  {
    "restaurant_id": 17284145,
    "restaurant_name": "Hong Kong Cafe",
    "cuisines": "Chinese, Seafood, Vegetarian",
    "average_costfortwo": 25,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.6,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 88
  },
  {
    "restaurant_id": 17284150,
    "restaurant_name": "House of China Restaurant II",
    "cuisines": "Chinese",
    "average_costfortwo": 10,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.8,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 153
  },
  {
    "restaurant_id": 17284158,
    "restaurant_name": "Jimmie's Hot Dogs",
    "cuisines": "",
    "average_costfortwo": 10,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.9,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 160
  },
  {
    "restaurant_id": 17284175,
    "restaurant_name": "Locos Grill & Pub",
    "cuisines": "American, Burger, Sandwich",
    "average_costfortwo": 25,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.5,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 57
  },
  {
    "restaurant_id": 17284179,
    "restaurant_name": "Longhorn Steakhouse",
    "cuisines": "American, Steak",
    "average_costfortwo": 25,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.5,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 58
  },
  {
    "restaurant_id": 17284197,
    "restaurant_name": "Mikata Japanese Steakhouse",
    "cuisines": "Japanese, Steak, Sushi",
    "average_costfortwo": 40,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.6,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 115
  },
  {
    "restaurant_id": 17284241,
    "restaurant_name": "Shogun Japanese Steak House",
    "cuisines": "Japanese, Steak, Sushi",
    "average_costfortwo": 40,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.5,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 51
  },
  {
    "restaurant_id": 17284390,
    "restaurant_name": "The Catch Seafood Room & Oyster Bar",
    "cuisines": "Seafood, Tapas, Bar Food",
    "average_costfortwo": 40,
    "currency": "Dollar($)",
    "has_tablebooking": "No",
    "has_online_delivery": "No",
    "aggregate_rating": 3.8,
    "rating_color": "Yellow",
    "rating_text": "Good",
    "votes": 250
  }
];

